### ISSUE TITLE
Make a file exporter component

### ISSUE THREAD

**Issue by felipelauten** [felipelauten/lottery-algorithm#2]
I believe that to adhere to SRP (Single Responsibility Principle), the main class shouldn't be responsible for writing files. 

We need to create a **FileExporter** class (or some different naming) that accepts a text string and writes it into the file system. It is this class responsibility to check if the output directory exists and creating it. We can add a boolean field to its API to set if the caller wants the output dir to be created or not. And if not, and the dir doesn't exist, throw an exception.

### Requirements

- Constructor that initialises the output dir, filename and optional field (with default true) that indicates if the output directory should be created if it doesn't exist.
- Functions to write different formats of data (for now just text, but leave a placeholder interface for more types of text data in the future, like Json, XML, etc.
- Should throw an exception if the instance is marked not to create the output dir and it doesn't exist.
- Unit tested, of course.

**Comment by krisJagoda** [comment]
Taking the task.

**Comment by krisJagoda** [comment]
Hi Felipe,
Please see my comments in code.

Functions to write different formats of data (for now just text, but leave a placeholder interface for more types of text data in the future, like Json, XML, etc. : this is not a simple implementation. I would need to know whether we are doing conversions from .txt to other formats (if so, which ones are acceptable: JSON? XML?). Just changing the end of the file I do not think would really convert it into the desired format acceptable by other software tools.

Once you respond to my comments in code, I will proceed with test coverage. Please note I have tested all methods and they work as expected. The unit tests are more complicated that I initially expected and mocking the 'fs' library is needed. See my initial tests. But I will do the full coverage once I understand how to do it properly.

Let me know what you think.

Thanks,
Krystian
