### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by krisJagoda** [felipelauten/lottery-algorithm#7]
To create a new class to read, validates and pass new values to the Lottery class.
This task is to remove the hardcoded values in index.ts:

const upperBoundary = 200_000;
const numbersToDraw = 199_900;

These values shall be taken from the user, also the user's input shall be validated accordingly.

**Comment by felipelauten** [comment]
I'm eager to see how this is done in node. Exactly what we need now. 👍

**Comment by krisJagoda** [comment]
This is not a complicated implementation. But I will finish with the previous task first. Thanks!
